### ISSUE TITLE
Understanding the results of MCEvidence code

### ISSUE THREAD

**Issue by surgithub** [yabebalFantaye/MCEvidence#1]
Hi,

I applied the MCEvidence code to some chain file, and got the following output:

Evidence[k=(1,2,3,4)] =  [-11.32384949 -11.22850661 -11.22165357 -11.23315178]

What are these four entries? How to get ln(B) from here? Please explain in detail.

Thanks.

**Comment by skroon** [comment]
These are the maximum likelihood estimates of the (log-)evidence based on using different values of k in the algorithm.  The algorithm is based on extracting information from the distances between nearby points in the chain.  For k=1, these are nearest-neighbour distance, for k>1, it is the distance to the k-th closest point in the chain.

**Comment by surgithub** [comment]
Thanks. I need some further clarification. I have read the paper 1704.03467. But it is not clear to me that how the ln(B) values are obtained in Table II from the MCEvidence code output? Please explain in detail with an example. For instance, when you run MCEvidence code on TT_lowTEB chains corresponding to base model, what is Evidence[k=(1,2,3,4)] = [????]. Then how do you find ln(B) = -0.7. It will be helpful for other users as well.

**Comment by yabebalFantaye** [comment]
The code that produces Table II is https://github.com/yabebalFantaye/MCEvidence/blob/master/planck_mcevidence.py
Each column in table II represents different data set while rows are for different models. To get a single column in Table II, we loop over models and store the k=1 value of Evidence[k=(1,2,3,4)] in a vector. We then subtract the maximum of this vector from all elements - hence the reason in table II why all values are either zero or negative number. 
For more information see the planck_mcevidence.py code.

**Comment by surgithub** [comment]
Thanks for the nice explanation. 

I have a MCMC chain file obtained by using certain prior ranges of parameters. I am able to process this chain with the default MCEvidence.py file by doing 

`python MCEvidence.py </path/to/chain>`

Please write where and how to supply the prior ranges of my parameters.

**Comment by skroon** [comment]
You probably want to use the "priorvolume" keyword when creating the
MCEvidence object for the calculation.  (See the code at the end of
MCEvidence.py for how to initialize and call the MCEvidence object.)

I hope that helps.

Steve

**Comment by yabebalFantaye** [comment]
I am closing this issue as I feel enough detail is given.
