### ISSUE TITLE
wrong output using planck chains

### ISSUE THREAD

**Issue by terryys** [yabebalFantaye/MCEvidence#2]
I am trying to calculate the evidence of Planck chains but I only get 0 for k=1,2,3,4. The following is my command and output:
python MCEvidence.py ~/temp/Downloads/base/plikHM_TTTEEE_lowTEB/base_plikHM_TTTEEE_lowTEB -k=5
INFO:__main__:getting params info from /home/user/syeung/temp/Downloads/base/plikHM_TTTEEE_lowTEB/base_plikHM_TTTEEE_lowTEB.ranges
INFO:__main__:getting prior volume using cosmomc *.ranges output
INFO:__main__:prior_volume=0.56410582

Using file:  /home/user/syeung/temp/Downloads/base/plikHM_TTTEEE_lowTEB/base_plikHM_TTTEEE_lowTEB
INFO:__main__:string passed. Loading chain from /home/user/syeung/temp/Downloads/base/plikHM_TTTEEE_lowTEB/base_plikHM_TTTEEE_lowTEB
INFO:__main__:mcsample: rootname=/home/user/syeung/temp/Downloads/base/plikHM_TTTEEE_lowTEB/base_plikHM_TTTEEE_lowTEB, idchain=0
INFO:__main__:chain array dimensions: 45979 x 33 =
INFO:__main__:requested nsamples=45979, ntotal_chian=45979
INFO:__main__:Prewhitenning chains using sample covariance matrix ..
INFO:__main__:   ln(B)[k=1] = 0.0
INFO:__main__:   ln(B)[k=2] = 0.0
INFO:__main__:   ln(B)[k=3] = 0.0
INFO:__main__:   ln(B)[k=4] = 0.0
* ln(B)[k] is the natural logarithm of the Baysian evidence estimated using the kth Nearest Neighbour.

Is it the proper way to do the calculation?

**Comment by yabebalFantaye** [comment]
Sorry for the late reply @terryys. The issue was due to a wrong exponential in the output as  #3 clearly pointed out. This bug is fixed now. Let me know if you have any other issues.
