### ISSUE TITLE
Wrong exponential in ouput?

### ISSUE THREAD

**Issue by mpauly** [yabebalFantaye/MCEvidence#3]
In the output of the CLI programm there appears a `np.exp()` that seems wrong to me. 
Specifically line 908
https://github.com/yabebalFantaye/MCEvidence/blob/master/MCEvidence.py#L908
This `np.exp()` appeared around two month ago and probably also is responsible for #2 .
Can you confirm this?

**Comment by yabebalFantaye** [comment]
@mpauly you are right, that was a mistake. Thank you for pointing that out. I corrected this mistake now and closed issue #2.
