### ISSUE TITLE
MCEvidence vs Other Sampling methods

### ISSUE THREAD

**Issue by antolonappan** [yabebalFantaye/MCEvidence#4]
Nested Sampling and Ellipsoidal nested sampling are the classical methods of finding Bayesian evidence. The MultiNest algorithm is capable of analyzing multimodal posteriors also. Could you please explain, what is the benefit of using MCEvidence over other sampling techniques.

**Comment by alanheavens** [comment]
MCEvidence is useful for post-processing of existing MCMC chains, which have typically been generated for the purpose of parameter inference, rather than Bayesian evidence.

**Comment by yabebalFantaye** [comment]
Closing it as I believe Alan's answer addresses fully the issue
