### ISSUE TITLE
Message about negative eigenvalues incorrect?

### ISSUE THREAD

**Issue by mpauly** [yabebalFantaye/MCEvidence#6]
With the latest commit I get an error about negative eigenvalues albeit all my eigenvalues being positive. I assume this is because of line https://github.com/yabebalFantaye/MCEvidence/blame/308ae8605ff09b5a75e9c84a3db94d87b6e742ff/MCEvidence.py#L677
that probably should read `if (eigenVal<0).any():`?

**Comment by yabebalFantaye** [comment]
Thank you for pointing this out. This issues is fixed now in the latest version.
