### ISSUE TITLE
Error in the prior volume calculation used for the tables?

### ISSUE THREAD

**Issue by ivandebono** [yabebalFantaye/MCEvidence#9]
Some of the prior volumes given in the planck_fullgrid tables don't match the values output by the module params_info.

e.g. For the model 'base_nnu_meffsterile_r' (ndim=9) with the data set 'plikHM_TT_lowTEB_lensing', the table says 62.587 but the module gives 35.30512685052.

**Comment by yabebalFantaye** [comment]
This is because in the planck_fullgrid tables we show the normalized priors (wrt the base model). The prior volume for the base model is 0.56410582.

**Comment by ivandebono** [comment]
Thank you. That settles the issue.
